### ISSUE TITLE
MIN_MINT_DYAD_DEPOSIT doesn't do anything

### ISSUE THREAD

**Issue by zobront** [DyadStablecoin/contracts-v3#14]
### Summary

The public `mint()` function includes a requirement that users must submit $5k of ETH in order to mint a new dNFT. However, there is no restriction on them immediately redeeming this deposit back into ETH by calling `redeemDeposit()`.

The only requirement is that they keep sufficient balance to avoid being liquidated, which is enforced independently from the `MIN_MINT_DYAD_DEPOSIT`.

The result is that a user can buy up the full supply of dNFTs for close to free, as they loop through:
- mint() => deposit $5k of ETH
- redeemDeposit() => cash out up to $5k of ETH

This becomes a greater risk depending how the `liquidation()` function is changed, based on #4.

### Recommendations

This relies heavily on how you decide to implement liquidations, as it's unclear whether they will solve for this use case.

In the event that liquidations do not solve this problem (which is my recommendation), consider requiring a minimum number of shares (or value of deposits) that must be maintained by all dNFTs at all times. This will ensure that a fixed amount of the deposited dollars stay in the vault.

**Comment by SharifElfouly** [comment]
I think this is solved by the new liquidation mechanism. you could mint it in a loop like you described but all your dnfts would be open for liquidation instantaneously.

**Comment by zobront** [comment]
I think it's the opposite, isn't it? In the new system, as long as you don't withdraw (into DYAD) and just redeem (into ETH) you'll never be liquidatable.

**Comment by SharifElfouly** [comment]
fixed by https://github.com/DyadStablecoin/contracts-v3/pull/25/files

**Comment by zobront** [comment]
Confirmed fix #25 (plus an additional push straight to main: https://github.com/DyadStablecoin/contracts-v3/commit/881163ceae7316b1b5781e32bd302b561b848721)

**Comment by zobront** [comment]
Confirmed fix with #25, https://github.com/DyadStablecoin/contracts-v3/commit/881163ceae7316b1b5781e32bd302b561b848721, and #30. 

The deposit minimum is still not a true invariant, as a user with minimum deposits could have their deposits lowered by the price of ETH falling. However, the goal of this check is to keep users from disengaging from the system, and there is no harm done or liquidation risk from it falling below the minimum, so this accomplishes that goal.
